config/routes.rb
Codingstack::Application.routes.draw do

  get "askquestions/new"

  get "oauths/oauth"

  get "oauths/callback"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "unanswered" => "askquestions#unanswer", :as => "unanswered"
  get "questions/tagged/:id" => "askquestions#tagged", :as => "questions/tagged"

  resources :users
  resources :sessions

  resources :askquestions do
    member do
      get 'vote_up'
      post 'vote_up'
      get 'vote_down'
      post 'vote_down'
      post 'views'
      get 'views'
    end
    resources :comments do
      member do
        put 'update_test'
      end
    end
    resources :answers do
      member do
        post 'vote_up'
        post 'vote_down'
        get 'vote_up'
        get 'vote_down'

      end
      member do
        get 'tick_status'
      end
    end

end
  resources :tags
  resources :session

  root :to => "askquestions#index"

match "oauth/callback" => "oauths#callback"
match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :askquestion_id, :user_id, :answer, :active


  validates :answer, :presence => true

  belongs_to :askquestion
  belongs_to :user
  has_many :votes, :as => :votable
  has_many :comments, :as => :commentable

  after_save :set_askquestion_delta_flag
  after_destroy :set_askquestion_delta_flag


  def set_askquestion_delta_flag
    askquestion.delta = true
    askquestion.save
  end


  def vote_calculate(question)
    arr = []
    cal_votes = Answer.find_all_by_askquestion_id(question)
    cal_votes.each do |vote|
      arr << [vote.votes.sum(:status), vote.id]
    end
    arr.sort
    arr2 = arr.sort{|x,y| y<=> x}

    vote_answer = []
    arr2.each do |x,y|
      vote_answer << Answer.find(y)
    end
    return vote_answer
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_filter :require_login, :except => [:new]
  skip_before_filter :verify_authenticity_token

  def new

    @question = Askquestion.find(params[:askquestion_id])
    @question.view_counter+=1
    @question.save
    @answer = Answer.new
    @answer_of_the_question = Answer.find_all_by_askquestion_id(params[:askquestion_id])
    @votes_on_answer = Answer.find_all_by_askquestion_id(params[:askquestion_id])
    @tags = Tag.all
    @answer_tick = @question.answers
    #@answer_votes = @question.answers.votes
    @comments = Comment.all
    @comment = Comment.new
  end

  def create
    #TODO create a before filter to check if the user is logged in.

    params[:answer][:user_id] = current_user.id if(params[:answer])

    params[:answer][:askquestion_id] = params[:askquestion_id] if(params[:askquestion_id])

    @answer = Answer.new(params[:answer])
    if @answer.save
      flash[:notice] = "Successfully answered the question."
      redirect_to new_askquestion_answer_path, :notice => "Answer has been posted"
    else
      flash[:error] = "Provide the answer."
      @question = Askquestion.find(params[:askquestion_id])
      @comments = Comment.all
      @comment = Comment.new
      @answer = Answer.new
      @answer_of_the_question = Answer.find_all_by_askquestion_id(params[:askquestion_id])
      @votes_on_answer = Answer.find_all_by_askquestion_id(params[:askquestion_id])
      @tags = Tag.all
      @answer_tick = @question.answers

      render :new
    end

  end



  def vote_up


    logger.info "=Ans_controller" * 20
    logger.info params.inspect
    logger.info current_user.inspect
    logger.info "" * 20
    logger.info "end" * 20

    @vote_up =  Answer.find(params[:id])
    @vote = @vote_up.votes.build
    @vote.user = current_user
    @vote.status = 1
    if @vote.save
      return redirect_to new_askquestion_answer_path, :notice => "Voted Up!"
    else
      #@subjects = Subject.find(:all)
      render :action => 'new'

    end
  end


  def vote_down
    @vote_down =  Answer.find(params[:id])
    @vote = @vote_down.votes.build
    @vote.user = current_user
    @vote.status = -1

    if @vote.save
      return redirect_to new_askquestion_answer_path, :notice => "Voted Down!"

    else
      #@subjects = Subject.find(:all)
      render :action => 'new'
    end

  end

  def tick_status

    @tick_status = Answer.find(params[:id])
    if (@tick_status.tick_status == 1)
      @tick_status.tick_status = nil
      if @tick_status.update_attributes(params[:answer_id])
      redirect_to new_askquestion_answer_path, :notice => "Answer DisApproved!"
    else
      render :action => 'new'
    end
    else
      @tick_status.tick_status = 1
      if @tick_status.update_attributes(params[:answer_id])
      redirect_to new_askquestion_answer_path, :notice => "Answer Approved!"
    else
      render :action => 'new'
    end
    end

  end



end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_editor.html.erb
<div class="answer-the-question">
  <p class="recent-question"><span class="answer-note">Answer the question</span></p>

  <div class="ask-question">
    <h2 class="a-y-question"></h2>

    <%= form_for @answer, :url => askquestion_answers_path(@askquestion_id) do |f| %>
        <% if @answer.errors.any? %>
            <div class="error_messages">
              <h2>Form is invalid, prohibited this record from being saved</h2>
              <ul>
                <% for message in @answer.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>



        <div class="field">
          <%= f.hidden_field :answer, id: "wmd-preview-input" %>
          <div class="wmd-panel">
            <div id="wmd-button-bar"></div>
            <textarea class="wmd-input" id="wmd-input"></textarea>
          </div>
          <div id="wmd-preview" class="wmd-panel wmd-preview">
          </div>
        </div>
        <div class="create-holder"> <span class="btn-holder">
                   <button class="create-btn create-new-answer" name="Create Askquestion" value="Create Askquestion"></button>
            <small>or</small>
            <button type="cancel" class="create-btn cancel-btn" name="#" value=""></button>
            </span>
          <!--<span class="click-to-add">-->
          <!--<label for="wiki">wikki</label>-->
          <!--<input type="checkbox" name="#" id="wiki" value="">-->
          <!--</span>-->
        </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
    (function () {

        var converter1 = Markdown.getSanitizingConverter();
        var editor1 = new Markdown.Editor(converter1);
        editor1.run();
        var converter2 = new Markdown.Converter();
        converter2.hooks.chain("preConversion", function (text) {
            return text.replace(/\b(a\w*)/gi, "*$1*");
        });
        converter2.hooks.chain("plainLinkText", function (url) {
            return "This is a link to " + url.replace(/^https?:\/\//, "");
        });
        var help = function () {
            alert("Do you need help?");
        }
        var editor2 = new Markdown.Editor(converter2, "-second", { handler:help });
        editor2.run();
    })();

</script>

app/views/answers/_answer_vote_rating.html.erb
<div class="rating-icon-holder">
  <ul class="a-q-flag">
    <li><a href="javascript:void(0);" data-id="<%= ans.id %>" data-type="Answer" class="flag">flag</a></li>
    <li><a href="#" class="link-icon">link</a></li>
  </ul>


  <% if current_user && current_user.id == @question.user_id  %>
      <% if ans.tick_status == 1 %>
          <%= link_to  "Tick", "javascript:void(0);", :class => "tick-colour" %>
      <% else %>
          <%= link_to  " Tick ", tick_status_askquestion_answer_path(@question.id, ans.id), :class => "tick-simple" %>
      <% end %>

  <% elsif ans.tick_status == 1 %>
      <%= link_to  " Tick ", "javascript:void(0);", :class => "tick-colour" %>
  <% end %>

  <div class="about-question">

    <span class="ans_<%= ans.id%>">

      <% if current_user && current_user.votes.where(votable_id: ans.id , Votable_type: "Answer").present? && ans.votes.present?  %>

          <% if current_user.votes.where(votable_id: ans.id , Votable_type: "Answer").last.status == 1 %>
              <input type="hidden" name="question_id" id="question_id" value='<%= @question.id %>' />
                <%#= link_to  "VOTE DOWN",  vote_down_askquestion_answer_path(@question.id, ans.id), :id => "ans_vote_down_#{ans.id}", :class => "unlike-down-answer" , :data => ans.id%>
                <%= link_to  "VOTE DOWN", 'javascript:void(0);', :id => "ans_vote_down_#{ans.id}", :class => "unlike-down-answer" , :data => ans.id%>

          <% elsif current_user.votes.where(votable_id: ans.id , Votable_type: "Answer").last.status == -1   %>

              <%#= link_to 'VOTE UP',   vote_up_askquestion_answer_path(@question.id, ans.id), :id => "ans_vote_up_#{ans.id}", :class => "like-up-answer", :data => ans.id  %>
              <%= link_to 'VOTE UP', 'javascript:void(0);', :id => "ans_vote_up_#{ans.id}", :class => "like-up-answer", :data => ans.id  %>
                <input type="hidden" name="answer_id" id="answer_id" value='<%= ans.id %>' />
          <% end %>
      <% else %>
            <%#= link_to 'VOTE UP',   vote_up_askquestion_answer_path(@question.id, ans.id), :id => "ans_vote_up_#{ans.id}", :class => "like-up-answer", :data => ans.id  %>
                <!--<input type="hidden" name="answer_id" id="answer_id" value='<%#= ans.id %>' />-->
            <%#= link_to  "VOTE DOWN",  vote_down_askquestion_answer_path(@question.id,ans.id), :id => "ans_vote_down_#{ans.id}", :class => "unlike-down-answer" , :data => ans.id%>
          <%= link_to 'VOTE UP', 'javascript:void(0);', :id => "ans_vote_up_#{ans.id}", :class => "like-up-answer", :data => ans.id  %>
          <input type="hidden" name="answer_id" id="answer_id" value='<%= ans.id %>' />
          <%= link_to  "VOTE DOWN", 'javascript:void(0);', :id => "ans_vote_down_#{ans.id}", :class => "unlike-down-answer" , :data => ans.id%>
      <% end %>
    </span>
  </div>
</div>

app/views/answers/_answer_with_comments.html.erb
<div class="middle-holder">
  <div class="rating-icon-holder">
    <ul class="a-q-flag">
      <li><a href="#" class="flag">flag</a></li>
      <li><a href="#" class="link-icon">link</a></li>
    </ul>

    <% if current_user && current_user.id == @question.user_id  %>
        <% if ans.tick_status == 1 %>
            <%= link_to  "Tick", "javascript:void(0);", :class => "tick-colour" %>
        <% else %>
            <%= link_to  " Tick ", tick_status_askquestion_answer_path(@question.id, ans.id), :class => "tick-simple" %>
        <% end %>

    <% elsif ans.tick_status == 1 %>
        <%= link_to  " Tick ", "javascript:void(0);", :class => "tick-colour" %>
    <% end %>

    <% logger.debug "Answer-"*20 %>

    <div class="about-question">

    </div>
  </div>
  <div class="user-question">
    <span class="user-img"><%= image_tag avatar_url(ans.user) %></span>
    <span class="post-heading"><%= raw(ans.answer) %></span>
    <!--Start --Comment-List -- Start-->
    <div class="comment-holder">
      <div class="comment-copy-Answer<%= ans.id%>">

        <input type="hidden" name="comment-question-id" id="comment-question-id" value='<%= ans.id %>' />

        <% @comments.each do |comment| %>
            <tr>

              <% if comment.commentable_id == ans.id && comment.commentable_type == "Answer"%>
                <div class="inner-c">

                  <% if current_user.present? && current_user.id == comment.user_id %>
                      <%= best_in_place comment, :description, :path => comment_path(answer_id: comment.commentable_id, id: comment) %>

                  <% else %>
                      <span><%=  comment.description %> </span>
                  <% end %>
                  <span class="by-post-user">
                    TEST TEST TEST
                            <a href="/users/<%= comment.user.id" class="us-name"><%= comment.user.email.gsub(/@.*/, "") %></a>
                            <a href="#" class="by-date-user"><%= comment.created_at.strftime('%b%e, %g at %H:%M') %> - <%= time_ago_in_words(comment.created_at) %></a> <img src="/assets/comment-edit.png">
                             </span>
                </div>

            <% end %>

        <% end %>

      </div>

      <div class="create-comment">
        <%= form_for  @comment, :url =>  comments_path(answer_id: ans.id) do |f| %>
            <% if @comment.errors.any? %>
                <div id="errorExplanation">
                  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
                    this post from being saved:</h2>
                  <ul>
                    <% @comment.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="txt-field4">

              <%= f.text_field :description, :class=> "answer_comment" %>
            </div>

            <%= f.submit :class => "create-btn comment-btn " %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/answers/_answer_with_status_tick.html.erb
<!--##################### First loop ###########################################-->

<% @answer_of_question.each do |ans| %>
    <% if ans.tick_status == 1 %>
        <div class="q-post">
          <div class="q-top">
            <div class="counter-holder">
              <ul class="counter-nav">
                <li><span class="answer_votes_<%= ans.id%>">Votes:<%= ans.votes.sum(:status) %> </span></li>
              </ul>
              <strong class="by-date"> <span class="u-name"><a href="#">pyroxicated</a> 245</span>
                <span>Asked<span class="ago-days"> <%= time_ago_in_words(ans.created_at) %> ago</span></span>
              </strong>
            </div>
            <div class="middle-holder">
              <div class="rating-icon-holder">
                <ul class="a-q-flag">
                  <li><a href="javascript:void(0);" data="Answer" class="flag">flag</a></li>
                  <li><a href="#" class="link-icon">link</a></li>
                </ul>



                <% if current_user && current_user.id == @question.user_id  %>
                    <% if ans.tick_status == 1 %>
                        <%= link_to  "Tick", tick_status_askquestion_answer_path(@question.id, ans.id), :class => "tick-colour" %>
                    <% else %>
                        <%= link_to  " Tick ", tick_status_askquestion_answer_path(@question.id, ans.id), :class => "tick-simple" %>
                    <% end %>

                <% elsif ans.tick_status == 1 %>
                    <%= link_to  " Tick ", tick_status_askquestion_answer_path(@question.id, ans.id), :class => "tick-colour" %>
                <% end %>

                <% logger.debug "Answer-"*20 %>

                <div class="about-question">

                </div>
              </div>
              <div class="user-question">
                <span class="user-img"> <%= image_tag avatar_url(ans.user) %></span>
                <span class="post-heading"><%= raw(ans.answer) %></span>
                <!--Start --Comment-List -- Start-->
                <div class="comment-holder">
                  <div class="comment-copy-Answer<%= ans.id%>">

                    <input type="hidden" name="comment-question-id" id="comment-question-id" value='<%= ans.id %>' />

                    <% @comments.each do |comment| %>
                        <tr>
                          <% logger.debug "Q-Comment_Q" * 8 %>
                          <% logger.debug comment.inspect %>
                          <% logger.debug  %>
                          <% logger.debug %>
                          <% logger.debug " End Q End "*15 %>

                          <% if comment.commentable_id == ans.id && comment.commentable_type == "Answer"%>
                            <div class="inner-c">

                              <% if current_user.present? && current_user.id == comment.user_id %>
                                  <%= best_in_place comment, :description, :path => comment_path(answer_id: comment.commentable_id, id: comment) %>

                              <% else %>
                                  <span><%=  comment.description %> </span>
                              <% end %>
                              <span class="by-post-user">
                            <a href="#" class="us-name"> <%= comment.user.email %></a>
                            <a href="#" class="by-date-user">Jan3 '10 at 23:56 <%= time_ago_in_words(comment.created_at) %></a> <img src="/assets/comment-edit.png">
                             </span>
                            </div>

                        <% end %>

                    <% end %>

                  </div>

                  <div class="create-comment">
                    <%= form_for  @comment, :url =>  comments_path(answer_id: ans.id) do |f| %>
                        <% if @comment.errors.any? %>
                            <div id="errorExplanation">
                              <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
                                this post from being saved:</h2>
                              <ul>
                                <% @comment.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                <% end %>
                              </ul>
                            </div>
                        <% end %>

                        <div class="txt-field4">

                          <%= f.text_field :description, :class=> "answer_comment" %>
                        </div>

                        <%= f.submit :class => "comment-btn" %>

                    <% end %>

                  </div>
                </div>

              </div>
            </div>
          </div>
          <div class="q-btm">&nbsp;</div>
        </div>
    <% end %>
<% end %>

<!--##################### END First Loop ###########################################-->

app/views/answers/_answers_of_question.html.erb
<!--##################### END First Loop ###########################################-->


<% @answer.vote_calculate(@question).each do |x|%>

        <div class="q-post">
          <div class="q-top">
            <div class="counter-holder">
              <ul class="counter-nav">
                <li><span class="answer_votes_<%= x.id%>">Votes:<%= x.votes.sum(:status) %> </span></li>
              </ul>
              <strong class="by-date"> <span class="u-name"><a href="#"><%= x.user.email %></a> <%= x.user.rating %></span>
                <span>Asked<span class="ago-days"> <%= time_ago_in_words(x.created_at) %> ago</span></span>
              </strong>
            </div>
            <div class="middle-holder">
              <div class="rating-icon-holder">
                <ul class="a-q-flag">
                  <li><a href="javascript:void(0);" data-id="<%= x.id %>" data-type="Answer" class="flag">flag</a></li>
                  <li><a href="#" class="link-icon">link</a></li>
                </ul>
            
                <%# logger.debug current_user.votes.present? %>

                <% if current_user && current_user.id == @question.user_id  %>
                    <% if x.tick_status == 1 %>
                        <%= link_to  " Tick ", "javascript:void(0);", :class => "tick-colour" %>
                    <% else %>
                        <%= link_to  " Tick ", "javascript:void(0);", :class => "tick-simple", :data_id => x.id %>
                    <% end %>

                <% elsif x.tick_status == 1 %>
                    <%= link_to  " Tick ", "javascript:void(0);", :class => "tick-colour" %>
                <% end %>

                <div class="about-question" id="answers_of_Question">

                    <span class="ans_<%= x.id%>">
                    <% if(current_user && current_user.votes.where(votable_id: x.id , Votable_type: "Answer").present? && x.votes.present? ) %>
                        <input type="hidden" name="<%= x.id %>_A_user_id" id="<%= x.id %>_A_user_id" value="<%= x.user_id %>" >
                        <input type="hidden" name="last_voted_<%= x.id %>" id="last_voted_<%= x.id %>" value='<%= current_user.votes.where(votable_id: x.id , Votable_type: "Answer").last.status %>' />

                        <% if current_user.votes.where(votable_id: x.id , Votable_type: "Answer").last.status == 1 %>
                            <input type="hidden" name="answer_id" id="answer_id" value='<%= x.id %>' />
                              <%= link_to  "VOTE DOWN", 'javascript:void(0);', :id => "ans_vote_down_#{x.id}", :class => "unlike-down-answer" , :data => x.id %>

                        <% elsif current_user.votes.where(votable_id: x.id , Votable_type: "Answer").last.status == -1   %>

                            <%= link_to 'VOTE UP', 'javascript:void(0);', :class => "like-up-answer", :id => "ans_vote_up_#{x.id}", :data => x.id  %>
                              <input type="hidden" name="answer_id" id="answer_id" value='<%= x.id %>' />

                        <% end %>
                    <% else %>
                          <%= link_to 'VOTE UP', 'javascript:void(0);', :id => "ans_vote_up_#{x.id}", :class => "like-up-answer"  , :data => x.id%>
                            <input type="hidden" name="answer_id" id="answer_id" value='<%= x.id %>' />
                          <%= link_to  "VOTE DOWN", 'javascript:void(0);' ,:id => "ans_vote_down_#{x.id}", :class => "unlike-down-answer" , :data => x.id%>
                    <% end %>
                    </span>
                </div>
              </div>
              <div class="user-question">
                <span class="user-img"> <%= image_tag avatar_url(x.user) %></span>
                <span class="post-heading"><%= raw(x.answer) %></span>
                <!--<///////// -- Comment loop --answer-- --//////>-->
                <div class="comment-holder">
                  <div class="comment-copy-Answer<%= x.id%>">


                    <% @comments.each do |comment| %>


                        <% if comment.commentable_id == x.id && comment.commentable_type == "Answer"%>

                            <div class="inner-c">
                              <% if current_user.present? && current_user.id == comment.user_id %>
                                  <span><%= best_in_place comment, :description, :path => comment_path(answer_id: comment.commentable_id, id: comment.id) %> </span>
                              <% else %>
                                  <span><%=  comment.description %> </span>
                              <% end %>

                              <span class="by-post-user">

                                            <a href="/users/<%= comment.user.id %>" class="us-name"> <%= comment.user.email %></a>
                                            <a href="#" class="by-date-user"><%= comment.created_at.strftime('%b%e, %g at %H:%M') %> - <%= time_ago_in_words(comment.created_at) %></a> <img src="/assets/comment-edit.png">
                                        </span>
                            </div>

                        <% end %>
                    <% end %>


                  </div>

                  <div class="create-comment">
                    <%= form_for  @comment, :url =>  comments_path(answer_id: x.id), :html => { :id => "new_comment_#{x.id}"} do |f| %>
                        <% if @comment.errors.any? %>
                            <div id="errorExplanation">
                              <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
                                this post from being saved:</h2>
                              <ul>
                                <% @comment.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                <% end %>
                              </ul>
                            </div>
                        <% end %>
                        <div class="txt-field4">
                          <%#= f.label :description %>
                          <!--<br />-->
                          <%= f.text_field :description, :class => "answer_comment" %>
                        </div>

                        <%= f.submit :class=>"comment-btn create-btn"%>

                    <% end %>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="q-btm">&nbsp;</div>
        </div>
  <%end %>

app/views/answers/_comments.html.erb
<div class="comment-copy-Askquestion<%=@question.id%>">
  <!--Start --Comment-List -- Start-->
  <input type="hidden" name="comment-question-id" id="comment-question-id" value='<%= @question.id %>' />

  <% @comments.each do |comment| %>
      <tr>
        <% logger.debug "Q-Comment_Q" * 8 %>
        <% logger.debug comment.inspect %>
        <% logger.debug  %>
        <% logger.debug %>
        <% logger.debug " End Q End "*15 %>

        <% if comment.commentable_id == @question.id && comment.commentable_type == "Askquestion"%>
          <div class="inner-c">

            <% if current_user.present? && current_user.id == comment.user_id %>
                <%= best_in_place  comment, :description, :path => comment_path(askquestion_id: comment.commentable_id, id: comment) %>

            <% else %>
                <span><%= comment.description %> </span>
            <% end %>
            <span class="by-post-user">
                            <a href="#" class="us-name"> <%= comment.user.email %></a>
                            <a href="#" class="by-date-user"><%= comment.created_at.strftime('%b%e, %g at %H:%M') %> = <%= time_ago_in_words(comment.created_at) %></a> <img src="/assets/comment-edit.png">
                      </span>
          </div>

      <% end %>

  <% end %>

</div>

<div class="create-comment">

  <%= form_for  @comment, :url =>  comments_path(askquestion_id: @question.id) do |f| %>
      <% if @comment.errors.any? %>
          <div id="errorExplanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
              this post from being saved:</h2>
            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="txt-field4">

        <%= f.text_field :description %>
      </div>

      <%= f.submit :class=>"comment-btn"%>

  <% end %>

</div>
            

app/views/answers/_question.html.erb
<div class="q-post">
  <div class="q-top">
    <div class="counter-holder">
      <ul class="counter-nav">
        <li><span class="votes_count_<%= @question && @question.id%>">votes: <%= @question && @question.votes.sum(:status) %></span></li>
        <li class="green-bg"><span >answers:  <%= @question && @question.answers && @question.answers.count %> </span></li>
        <li><span id="views_count">views: <%= @question && @question.view_counter %></span></li>
      </ul>
      <strong class="by-date"> <span class="u-name"><a href="/users/<%= @question.user.id %>"><%= @question.user.email.gsub(/@.*/, "") %></a> <%= @question.user.rating %></span>
        <span>Asked<span class="ago-days"> <%= time_ago_in_words(@question.created_at) %> ago</span></span>
      </strong>
    </div>

    <div class="middle-holder">
      <div class="rating-icon-holder">


        <%=render :partial => "vote_rating"%>

      </div>
      <div class="user-question">
        <span class="user-img"><%= image_tag avatar_url(@question.user) %></span>

        <p class="question-txt"> <%= raw(@question.title) %> </p>
      </div>
      <div class="post-txt">
        <span class="post-heading"><%= raw(@question.title) %></span>

        <div class="post-discription">
          <!--<textarea class="post-info" cols="8" rows="8"></textarea>-->
          <span class="post-heading"><%= raw(@question.description) %></span>
        </div>
        <div class="comment-holder">
          <div class="comment-copy-Askquestion<%=@question.id%>">
            <!--Start --Comment-List -- Start-->
            <input type="hidden" name="comment-question-id" id="comment-question-id" value='<%= @question.id %>' />

            <% @comments.each do |comment| %>

              <% if comment.commentable_id == @question.id && comment.commentable_type == "Askquestion"%>
                <div class="inner-c">

                  <% if current_user.present? && current_user.id == comment.user_id %>
                   <%= best_in_place comment, :description, :path => comment_path(askquestion_id: comment.commentable_id, id: comment) %>

                  <% else %>
                    <span><%= comment.description %> </span>
                  <% end %>
                  <span class="by-post-user">
                        <a href="/users/<%= @question.user.id %>" class="us-name"> <%= comment.user.email.gsub(/@.*/, "") %></a>
                        <a href="#" class="by-date-user"><%= comment.created_at.strftime('%b%e, %g at %H:%M') %> - <%= time_ago_in_words(comment.created_at) %></a> <img src="/assets/comment-edit.png">
                  </span>
                </div>

              <% end %>

            <% end %>

          </div>

          <div class="create-comment">

              <%= form_for  @comment, :url =>  comments_path(askquestion_id: @question.id) do |f| %>

                  <% if @comment.errors.any? %>
                      <div id="errorExplanation">
                        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
                          this post from being saved:</h2>
                        <ul>
                          <% @comment.errors.full_messages.each do |msg| %>
                              <li><%= msg %></li>
                          <% end %>
                        </ul>
                      </div>
                  <% end %>

                  <div class="txt-field4">

                    <%= f.text_field :description %>
                  </div>

                  <%= f.submit :class=>"comment-btn create-btn"%>

              <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="q-btm">&nbsp;</div>
</div>