config/routes.rb
Codingstack::Application.routes.draw do

  get "askquestions/new"

  get "oauths/oauth"

  get "oauths/callback"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "unanswered" => "askquestions#unanswer", :as => "unanswered"
  get "questions/tagged/:id" => "askquestions#tagged", :as => "questions/tagged"

  resources :users
  resources :sessions

  resources :askquestions do
    member do
      get 'vote_up'
      post 'vote_up'
      get 'vote_down'
      post 'vote_down'
      post 'views'
      get 'views'
    end
    resources :comments do
      member do
        put 'update_test'
      end
    end
    resources :answers do
      member do
        post 'vote_up'
        post 'vote_down'
        get 'vote_up'
        get 'vote_down'

      end
      member do
        get 'tick_status'
      end
    end

end
  resources :tags
  resources :session

  root :to => "askquestions#index"

match "oauth/callback" => "oauths#callback"
match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/askquestion.rb
class Askquestion < ActiveRecord::Base
  attr_accessible :title,:description,:tag,:view_counter,:votes,:answer_counter,:user_id,:tag_names

  validates :title, :presence => true
  #validates :description, :presence => true
  validates :tag_names, :presence => true

  validates :title, :length => { :minimum => 5 }
  #validates :tag_names, :length => { :minimum => 2  }

  #validates :description, :length => { :minimum => 5  }




  has_many :votes, :as => :votable
  has_many :comments, :as => :commentable
  belongs_to :user
  has_many :askquestion_tags,:dependent =>:destroy
  has_many :tags, :through => :askquestion_tags
  has_many :answers

  attr_writer :tag_names


  attr_reader :tag_names




  # define_index do
  #   indexes title, sortable: true
  #   indexes description
  #   indexes answers.answer, as: :answer
  #   indexes tags.name, as: :tag
  #   set_property :delta => true

  # end











  #def to_indexed_json
  #  a = to_json(methods: [:answer])
  #  puts "#{'$' * 100}"
  #  puts a
  #  puts "#{'$' * 100}"
  #end
  #
  # def answer
  #  answers.collect{ |ans| ans.answer }
  #  tags.collect{|t| t.name}
  #  user.email
  
  #  Askquestion.first.tags.map(&:name).join(", ")
  #  user.email
  # end





  # def tag_names=(tokens)
  #   self.tag_ids = Tag.ids_from_tokens(tokens)
  # end









  after_save :assign_tags
def tag_names
  @tag_names || tags.map(&:name).join(' ')
end






  private
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\s+/).map do |name|
        Tag.find_or_create_by_name(name)
      end
      self.tags.each do |t|
        t.counter+=1
        t.save
      end
    end
  end












#validate :presence_of_tag_in_askquestion

#def presence_of_tag_in_askquestion
#  errors.add :tag, "must be a valid id" if self.tag_questions.blank?
#  errors.add :developed_bugs_id, "must be a valid developer id" if self.developer.blank?
end

app/controllers/askquestions_controller.rb
class AskquestionsController < ApplicationController

  before_filter :require_login, :except => [:index,:new]

  skip_before_filter :verify_authenticity_token

  def new

  # ['{ %%%% -- '*33, Rails.configuration.session_options[:key], Rails.configuration.secret_token, request.host, session, request.cookie_jar['_codingstack_session'], '% -- '*33].each{|x| logger.debug x.inspect}
  # request.cookie_jar.each{|x, y| logger.debug x + ' ... ' + y.inspect}

    @askquestion = Askquestion.new

  end

  def unanswer
    @askquestions = Askquestion.page(params[:page]).per_page(6).order('created_at DESC')
  end

  def tagged
    @askquestions = Askquestion.page(params[:page]).per_page(6).order('created_at DESC')
    @tag = Tag.find(params[:id])

  end

  def create
    
    #['% -- '*33, session, '% -- '*33].each{|x| logger.debug x.inspect}
    #
    #if !logged_in?
    #  session[:return_to_url] = request.url if Config.save_return_to_url
    #  self.send(Config.not_authenticated_action)
    #  return
    #end
    #
    #['% -- '*33, session, '% -- '*33].each{|x| logger.debug x.inspect}

    #return render :json => params
    #return render :json => params
    #return render :json => session

    @askquestion = current_user.askquestions.build(params[:askquestion])

    # will be use in future
    # @temp = 0
    

        # if @temp==0
        #   @tag= Tag.new
        #   @tag.counter=1
        #   @tag.askquestion_tags= @askquestion.tag
        # en
    #     @askquestion.tag.each do |q|
           # # @tag.askquestion_tags= @askquestion.tag
    #    end
#        break

      
# ##        create(@tag)
#       end
#     end
       
    # @tag=Tag.all
    # @tag.each do |tag|
    #   tag.counter += 1
    #   tag.save
    # end

      














      # @tag=Tag.all
      # @tag.each do |tag|
      #   if tag.name == @askquestion.tag.split
      #     tag.counter=tag.counter+1
      #     tag.save
      #   end
      # end


    if @askquestion.save
      #return render :json=> params
      flash[:notice] = "Successfully created question."
      redirect_to askquestions_path, :notice => "New question has been created"
    else
      #return render :json=> params
      render :new
    end

  end

  def index
    @tags = Tag.all
    @recent_users = User.order('created_at DESC').limit(5).all
    #return render :json => params
    if(params[:search]).present?
    @askquestions = Askquestion.search(params[:search], order: :title,:page => params[:page], :per_page => 6, field_weights: {title: 20, description: 10, tag: 5})

    else

      @askquestions = Askquestion.page(params[:page]).per_page(6).order('created_at DESC')

      #@askquestions = Askquestion.paginate(:page => params[:page], :per_page => 5)

    end


    #@askquestions = Askquestion.search(params)


    #@askquestions = Askquestion.page(params[:page]).per_page(6)



    #@askquestions = Askquestion.paginate(:page => params[:page], :per_page => 5)



    #@askquestion = Askquestion.find(params[:id])----------------------  gillani before pagination
    #@count=Askquestion.count
  end




  def vote_down

     #logger.info "=" * 20
     #logger.info params.inspect
     #logger.info "end" * 20


      @vote_down =  Askquestion.find(params[:id])
      @vote = @vote_down.votes.build
      @vote.user = current_user
      @vote.status = -1
      if @vote.save
        return redirect_to :back, :notice => "Voted Down!"
      else
        #@subjects = Subject.find(:all)
        render :action => 'new'

      end

  end
def vote_up

     #logger.info "=" * 20
     #logger.info params.inspect
     #logger.info "end" * 20


      @vote_down =  Askquestion.find(params[:id])
      @vote = @vote_down.votes.build
      @vote.user = current_user
      @vote.status = 1
      if @vote.save
        return redirect_to :back, :notice => "Voted Up!"
      else
        #@subjects = Subject.find(:all)
        render :action => 'new'

      end

  end
#def vote_down
#  @vote_down =  Askquestion.find(params[:askquestion_id])
#  @vote_down.votes = @vote_down.votes - 1
#  if @vote_down.update_attributes(params[:vote_down])
#    redirect_to new_askquestion_answer_path
#  else
#    #@subjects = Subject.find(:all)
#    render :action => 'new'
#  end
#
#end
#
#def views
#
#  @views =  Askquestion.find(params[:askquestion_id])
#  @views.view_counter = @views.view_counter + 1
#  if @views.update_attributes(params[:views])
#    #redirect_to :action => 'new', :id => @vote_up
#    redirect_to new_askquestion_answer_path
#  else
#    #@subjects = Subject.find(:all)
#    render :action => 'new'
#  end
#
#end



end

app/helpers/askquestions_helper.rb
module AskquestionsHelper
end

app/views/askquestions/Back_vote_rating.html.erb
<div class="rating-icon-holder">
  <ul class="a-q-flag">
    <li><a href="#" class="flag">flag</a></li>
    <li><%= link_to 'VIEWS', views_askquestion_path(question.id), :class => "eye" %>
      <input type="hidden" name="question_id" id="question_id" value='<%= question.id %>'/></li>
  </ul>

  <a href="#" class="rating"><img src="/assets/star-icon.png" width="20" height="20" alt="image"></a>

  <div class="about-question">
       <span class="ques_<%= question.id %>">
          <input type="hidden" class="rating" name="<%= question.id %>_Q_user_id" id="<%= question.id %>_Q_user_id" value='<%= @question.user.id %>'/>
          <% if current_user && current_user.votes.where(votable_id: question.id, Votable_type: "Askquestion").present? %>

              <% if current_user.votes.where(votable_id: question.id, Votable_type: "Askquestion").last.status == 1 %>
                  <input type="hidden" class="rating" name="question_id" id="question_id" value='<%= question.id %>'/>
                    <%= link_to "VOTE DOWN", 'javascript:void(0);', :class => "unlike-down", :data => question.id %>

              <% elsif current_user.votes.where(votable_id: question.id, Votable_type: "Askquestion").last.status == -1 %>

                  <%= link_to 'VOTE UP', 'javascript:void(0);', :class => "like-up", :data => question.id %>
                    <input type="hidden" class="rating" name="question_id" id="question_id" value='<%= question.id %>'/>
              <% end %>
          <% else %>
              <%= link_to 'VOTE UP', 'javascript:void(0);', :class => "like-up", :data => question.id %>
                <input type="hidden"  name="question_id" id="question_id" value='<%= question.id %>'/>
                <%= link_to "VOTE DOWN", 'javascript:void(0);', :class => "unlike-down", :data => question.id %>
          <% end %>
       </span>
  </div>
</div>

app/views/askquestions/index.html.erb
<%= stylesheet_link_tag "prettify.css" %>
<%#= stylesheet_link_tag "style.css" %>
<%#= stylesheet_link_tag "demo.css" %>



<script type="text/javascript">
    $(document).ready(function () {

        $(".like-up").click(function (e) {
            e.preventDefault();
            var question_id =  $(this).attr('data');
            alert(question_id);
            //alert(question_id);
            $(this).hide();
            $.ajax({
                type: 'POST',
                url: $(this).attr('href'),
                success:function (data) {
                    alert(question_id);
                    alert(data);
                   $('.vote_question').html("Votes: "+ data);
//                   $('.about-question').html( <%#= link_to  "VOTE DOWN",  vote_down_askquestion_path(question.id), :class => "unlike-down" %>);



                }

            });



        });


        $(".unlike-down").click(function (e) {
            e.preventDefault();
            var question_id =  $(this).attr('data');
            $(this).toggle();
           //$('.data').find(question_id).show();
//            $(this).click();
//            $(this).show();

            $("#like-ups-"+question_id).show();

            alert("like-ups-"+question_id);
            $("#like-ups-"+question_id).show();

//            $(".like-up").find($("#like-ups-"+question_id)).show();

            $.ajax({
                type: 'POST',
                url: $(this).attr('href'),
                success:function (data) {
                    $('.vote_question').html("Votes: "+ data);
//                    $('.about-question').html("<%#= link_to 'VOTE UP',   vote_up_askquestion_path(question.id), :class => "like-up", :data => question.id, :id => "like-ups-#{question.id}"  %>")
//                    $("#like-ups-"+question_id).show();

                    //$(".unlike-down").hide();
//                    $("#like-ups-"+question_id).click();
                   // $("#like-ups-"+question_id).show();
                    //alert("like-ups-"+question_id);
                }

            });


        });




    });
</script>

<body class="bg-2" onload="prettyPrint()">
<div id="wrapper">
  <section id="main">
    <article id="content">
      <div class="holder-2">
        <p class="recent-question"><span>recent questions</span><%=@askquestions.count%>.</p>
        <ul class="active-question">
          <li><a href="#" class="active">active</a></li>
          <li><a href="#">hot</a></li>
        </ul>
      </div>
      <div class="ask-question"><span class="tell-question">What is your question? Be descriptive.</span>

        <form method="post" action="#">
          <input type="submit" name="#" value="" class="sbmt-btn">
          <input type="text" name="#" value="" class="txt-field">
        </form>
      </div>
      <%= form_tag askquestions_path, method: :get do %>
          <div class="field">
            <%= text_field_tag :search, params[:search], data: {autocomplete_source: Askquestion.order(:title).map(&:title)} %>
            <%= submit_tag "Search", name: nil %>
      <% end %>
      <div class="apple_pagination">
        <%= will_paginate @askquestions, :container => false %>
      </div>

      <% @askquestions.each do |question| %>
          <div class="q-post-holder">
            <div class="q-post">
              <div class="q-top">
                <div class="counter-holder">
                  <ul class="counter-nav">
                    <%# logger.debug "PPPPPPPPPPPPP * 8  %>

                    <li><span class="vote_question"> Votes: <%= question.votes.sum(:status) %> </span></li>
                    <li class="green-bg"><span>Answer: <%= question.answers.count %></span></li>
                    <li><span>View: <%= question.view_counter %></span></li>
                  </ul>
                  <strong class="by-date"> <span class="u-name"><a href="#"><%= question.user.username %></a> 245</span>
                    <span>Asked<span class="ago-days"> <%= time_ago_in_words(question.created_at) %> ago</span></span>
                  </strong>
                </div>
                <div class="middle-holder">
                  <div class="user-question">
                    <span class="user-img"><img src="/assets/img-1.jpg" width="42" height="42" alt="image"/></span>

                    <p class="question-txt ">
                      <a href=<%=new_askquestion_answer_path(question.id) %>><%= raw(question.title) %></a>

                    </p>
                  </div>
                  <div class="tags-holder"><span class="tag-name">tags:</span>
                    <ul class="question-tags">

                        <% question.tags.each do |a| %>
                          <li><a href="<%=questions_tagged_path(a)%>"><%= a.name %></a></li>
                          <% end %>
                      <!--<li><a href="#">tag 2</a></li>-->
                    </ul>
                    <div class="about-question">

                      <% logger.debug "-QUESTION-"*20 %>
                      <%# logger.debug current_user.votes.where(votable_id:question.id ,Votable_type: "Askquestion").present?  %>
                      <% logger.debug "first if statement" * 8 %>
                      <% logger.debug current_user.present?  %>
                      <% logger.debug  !question.votes.blank?   %>
                      <%# logger.debug current_user.votes.present? %>
                      <% logger.debug "f" * 8 %>
                      <% logger.debug " " * 8%>
                      <%# logger.debug current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status %>
                      <% logger.debug "=" * 15 %>
                      <%# logger.debug current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status if current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.present? %>
                      <% logger.debug  "8" * 8  %>
                      <% logger.debug " End Q End "*15 %>
                    <% if current_user && current_user.votes.where(votable_id:question.id ,Votable_type: "Askquestion").present?   %>

                          <% if current_user.votes.where(votable_id:question.id , Votable_type: "Askquestion").last.status == 1 %>
                              <input type="hidden" name="question_id" class="question_id" value='<%= question.id %>' />
                              <%= link_to  "VOTE DOWN",  vote_down_askquestion_path(question.id), :class => "unlike-down", :data => question.id %>

                          <% elsif current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status == -1   %>

                              <%= link_to 'VOTE UP',   vote_up_askquestion_path(question.id), :class => "like-up", :data => question.id, :id => "like-ups-#{question.id}", :remote =>true  %>
                              <input type="hidden" name="question_id" class ="question_id" value='<%= question.id %>' />
                         <% end %>
                    <% else %>
                          <%= link_to 'VOTE UP',   vote_up_askquestion_path(question.id), :class => "like-up" , :data => question.id %>
                          <input type="hidden" name="question_id" id="question_id" value='<%= question.id %>' />
                          <%= link_to  "VOTE DOWN",  vote_down_askquestion_path(question.id), :class => "unlike-down" , :data => question.id%>
                    <% end %>

                    </div>
                  </div>
                </div>
              </div>
              <div class="q-btm">&nbsp;</div>
            </div>
          </div>
      <% end %>
      <span class="review">See the <a href="#">full list of questions</a> or <a href="#">browse by tags</a> Help us answer <a href="#">Unanswered
        questions</a> </span>
    </article>
    <aside id="sidebar">
      <div class="about-c-s">
        <div class="bg-top">&nbsp;</div>
        <div class="bg-center"><strong class="logo2"><a href="#">coding stack</a></strong>

          <p>Questions and Answers regarding any tool, any language or any framework. It's 100% free, no registration
            required.</p>
        </div>
        <div class="bg-btm">&nbsp;</div>
      </div>
      <div class="own-site"><span>create your own question answer site in 10 seconds for free</span></div>
      <div class="search-site">
        <%= form_tag askquestions_path, method: :get do %>
          <span class="st-site">search the site</span>
          <div class="search-holder">
          
          <div class="field">
            <%= text_field_tag :search, params[:search], data: {autocomplete_source: Askquestion.order(:title).map(&:title)}, :class => 'inputField' %>
      
            <input type="submit" name="#" value="" class="search-btn" style="margin-left:-10px;">
          </div>
          </div>
        <% end %>
      </div>
      <div class="tags-title">
        <ul class="tags-nav">
          <% @tags.each do |t|%>
            <li><a href="<%=questions_tagged_path(t)%>"><%=t.name%></a></li>
          <%end%>
        </ul>
      </div>
      <div class="user-holder"><strong class="user-heading">Top 5 users</strong>
        <ul class="user-bio">
          <li><span class="user-icon"><img src="/assets/img-1.jpg" width="34" height="33" alt="image"/></span>
            <span class="user-proxi"><a href="#">pyroxicated</a>(265)</span></li>
        </ul>
      </div>
      <div class="user-holder"><strong class="user-heading">Recent users</strong>
        <ul class="user-bio">
        <% @recent_users.each do |recent_user|%>
          <li><span class="user-icon"><img src="/assets/img-1.jpg" width="34" height="33" alt="image"/></span>
            <span class="user-proxi"><a href="#"><%= recent_user.username%></a>joined <%= time_ago_in_words(recent_user.created_at)%> ago</span></li>
        <%end%>
        </ul>
      </div>
      <div class="stay-us"><span class="stay-heading">Stay in touch</span>

        <div class="facebook-plugin"><img src="/assets/coding-stack-img.png" width="271" height="60" alt="facebook">
        </div>
        <span class="stay-heading">subscribe</span> <a href="#" class="rss-field">Subscribe to all questions</a></div>
    </aside>
  </section>
</div>
</body>

app/views/askquestions/tagged.html.erb
      <div class="apple_pagination">
        <%= will_paginate @askquestions, :container => false %>
      </div>

      <% @askquestions.each do |question| %>
      <% if question.tags.include?(@tag) %>
          <div class="q-post-holder">
            <div class="q-post">
              <div class="q-top">
                <div class="counter-holder">
                  <ul class="counter-nav">
                    <%# logger.debug "PPPPPPPPPPPPP * 8  %>

                    <li><span class="vote_question"> Votes: <%= question.votes.sum(:status) %> </span></li>
                    <li class="green-bg"><span>Answer: <%= question.answers.count %></span></li>
                    <li><span>View: <%= question.view_counter %></span></li>
                  </ul>
                  <strong class="by-date"> <span class="u-name"><a href="#"><%= question.user.username %></a> 245</span>
                    <span>Asked<span class="ago-days"> <%= time_ago_in_words(question.created_at) %> ago</span></span>
                  </strong>
                </div>
                <div class="middle-holder">
                  <div class="user-question">
                    <span class="user-img"><img src="/assets/img-1.jpg" width="42" height="42" alt="image"/></span>

                    <p class="question-txt ">
                      <a href=<%=new_askquestion_answer_path(question.id) %>><%= raw(question.title) %></a>

                    </p>
                  </div>
                  <div class="tags-holder"><span class="tag-name">tags:</span>
                    <ul class="question-tags">

                        <% question.tags.each do |a| %>
                          <li><a href="<%=questions_tagged_path(a)%>"><%= a.name %></a></li>
                          <% end %>
                      <!--<li><a href="#">tag 2</a></li>-->
                    </ul>
                    <div class="about-question">

                      <% logger.debug "-QUESTION-"*20 %>
                      <%# logger.debug current_user.votes.where(votable_id:question.id ,Votable_type: "Askquestion").present?  %>
                      <% logger.debug "first if statement" * 8 %>
                      <% logger.debug current_user.present?  %>
                      <% logger.debug  !question.votes.blank?   %>
                      <%# logger.debug current_user.votes.present? %>
                      <% logger.debug "f" * 8 %>
                      <% logger.debug " " * 8%>
                      <%# logger.debug current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status %>
                      <% logger.debug "=" * 15 %>
                      <%# logger.debug current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status if current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.present? %>
                      <% logger.debug  "8" * 8  %>
                      <% logger.debug " End Q End "*15 %>
                    <% if current_user && current_user.votes.where(votable_id:question.id ,Votable_type: "Askquestion").present?   %>

                          <% if current_user.votes.where(votable_id:question.id , Votable_type: "Askquestion").last.status == 1 %>
                              <input type="hidden" name="question_id" class="question_id" value='<%= question.id %>' />
                              <%= link_to  "VOTE DOWN",  vote_down_askquestion_path(question.id), :class => "unlike-down", :data => question.id %>

                          <% elsif current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status == -1   %>

                              <%= link_to 'VOTE UP',   vote_up_askquestion_path(question.id), :class => "like-up", :data => question.id, :id => "like-ups-#{question.id}", :remote =>true  %>
                              <input type="hidden" name="question_id" class ="question_id" value='<%= question.id %>' />
                         <% end %>
                    <% else %>
                          <%= link_to 'VOTE UP',   vote_up_askquestion_path(question.id), :class => "like-up" , :data => question.id %>
                          <input type="hidden" name="question_id" id="question_id" value='<%= question.id %>' />
                          <%= link_to  "VOTE DOWN",  vote_down_askquestion_path(question.id), :class => "unlike-down" , :data => question.id%>
                    <% end %>

                    </div>
                  </div>
                </div>
              </div>
              <div class="q-btm">&nbsp;</div>
            </div>
          </div>
      <% end %>
      <% end %>

app/views/askquestions/unanswer.html.erb
      <div class="apple_pagination">
        <%= will_paginate @askquestions, :container => false %>
      </div>

      <% @askquestions.each do |question| %>
      <% if question.answers.blank?%>
          <div class="q-post-holder">
            <div class="q-post">
              <div class="q-top">
                <div class="counter-holder">
                  <ul class="counter-nav">
                    <%# logger.debug "PPPPPPPPPPPPP * 8  %>

                    <li><span class="vote_question"> Votes: <%= question.votes.sum(:status) %> </span></li>
                    <li class="green-bg"><span>Answer: <%= question.answers.count %></span></li>
                    <li><span>View: <%= question.view_counter %></span></li>
                  </ul>
                  <strong class="by-date"> <span class="u-name"><a href="#"><%= question.user.username %></a> 245</span>
                    <span>Asked<span class="ago-days"> <%= time_ago_in_words(question.created_at) %> ago</span></span>
                  </strong>
                </div>
                <div class="middle-holder">
                  <div class="user-question">
                    <span class="user-img"><img src="/assets/img-1.jpg" width="42" height="42" alt="image"/></span>

                    <p class="question-txt ">
                      <a href=<%=new_askquestion_answer_path(question.id) %>><%= raw(question.title) %></a>

                    </p>
                  </div>
                  <div class="tags-holder"><span class="tag-name">tags:</span>
                    <ul class="question-tags">

                        <% question.tags.each do |a| %>
                          <li><a href="<%=questions_tagged_path(a)%>"><%= a.name %></a></li>
                          <% end %>
                      <!--<li><a href="#">tag 2</a></li>-->
                    </ul>
                    <div class="about-question">

                      <% logger.debug "-QUESTION-"*20 %>
                      <%# logger.debug current_user.votes.where(votable_id:question.id ,Votable_type: "Askquestion").present?  %>
                      <% logger.debug "first if statement" * 8 %>
                      <% logger.debug current_user.present?  %>
                      <% logger.debug  !question.votes.blank?   %>
                      <%# logger.debug current_user.votes.present? %>
                      <% logger.debug "f" * 8 %>
                      <% logger.debug " " * 8%>
                      <%# logger.debug current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status %>
                      <% logger.debug "=" * 15 %>
                      <%# logger.debug current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status if current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.present? %>
                      <% logger.debug  "8" * 8  %>
                      <% logger.debug " End Q End "*15 %>
                    <% if current_user && current_user.votes.where(votable_id:question.id ,Votable_type: "Askquestion").present?   %>

                          <% if current_user.votes.where(votable_id:question.id , Votable_type: "Askquestion").last.status == 1 %>
                              <input type="hidden" name="question_id" class="question_id" value='<%= question.id %>' />
                              <%= link_to  "VOTE DOWN",  vote_down_askquestion_path(question.id), :class => "unlike-down", :data => question.id %>

                          <% elsif current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status == -1   %>

                              <%= link_to 'VOTE UP',   vote_up_askquestion_path(question.id), :class => "like-up", :data => question.id, :id => "like-ups-#{question.id}", :remote =>true  %>
                              <input type="hidden" name="question_id" class ="question_id" value='<%= question.id %>' />
                         <% end %>
                    <% else %>
                          <%= link_to 'VOTE UP',   vote_up_askquestion_path(question.id), :class => "like-up" , :data => question.id %>
                          <input type="hidden" name="question_id" id="question_id" value='<%= question.id %>' />
                          <%= link_to  "VOTE DOWN",  vote_down_askquestion_path(question.id), :class => "unlike-down" , :data => question.id%>
                    <% end %>

                    </div>
                  </div>
                </div>
              </div>
              <div class="q-btm">&nbsp;</div>
            </div>
          </div>
      <% end %>
      <% end %>