config/routes.rb
Codingstack::Application.routes.draw do

  get "askquestions/new"

  get "oauths/oauth"

  get "oauths/callback"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "unanswered" => "askquestions#unanswer", :as => "unanswered"
  get "questions/tagged/:id" => "askquestions#tagged", :as => "questions/tagged"

  resources :users
  resources :sessions

  resources :askquestions do
    member do
      get 'vote_up'
      post 'vote_up'
      get 'vote_down'
      post 'vote_down'
      post 'views'
      get 'views'
    end
    resources :comments do
      member do
        put 'update_test'
      end
    end
    resources :answers do
      member do
        post 'vote_up'
        post 'vote_down'
        get 'vote_up'
        get 'vote_down'

      end
      member do
        get 'tick_status'
      end
    end

end
  resources :tags
  resources :session

  root :to => "askquestions#index"

match "oauth/callback" => "oauths#callback"
match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :askquestion_id, :user_id, :answer, :active


  validates :answer, :presence => true

  belongs_to :askquestion
  belongs_to :user
  has_many :votes, :as => :votable
  has_many :comments, :as => :commentable

  after_save :set_askquestion_delta_flag
  after_destroy :set_askquestion_delta_flag


  def set_askquestion_delta_flag
    askquestion.delta = true
    askquestion.save
  end


  def vote_calculate(question)
    arr = []
    cal_votes = Answer.find_all_by_askquestion_id(question)
    cal_votes.each do |vote|
      arr << [vote.votes.sum(:status), vote.id]
    end
    arr.sort
    arr2 = arr.sort{|x,y| y<=> x}

    vote_answer = []
    arr2.each do |x,y|
      vote_answer << Answer.find(y)
    end
    return vote_answer
  end

end

app/models/askquestion.rb
class Askquestion < ActiveRecord::Base
  attr_accessible :title,:description,:tag,:view_counter,:votes,:answer_counter,:user_id,:tag_names

  validates :title, :presence => true
  #validates :description, :presence => true
  validates :tag_names, :presence => true

  validates :title, :length => { :minimum => 5 }
  #validates :tag_names, :length => { :minimum => 2  }

  #validates :description, :length => { :minimum => 5  }




  has_many :votes, :as => :votable
  has_many :comments, :as => :commentable
  belongs_to :user
  has_many :askquestion_tags,:dependent =>:destroy
  has_many :tags, :through => :askquestion_tags
  has_many :answers

  attr_writer :tag_names


  attr_reader :tag_names




  # define_index do
  #   indexes title, sortable: true
  #   indexes description
  #   indexes answers.answer, as: :answer
  #   indexes tags.name, as: :tag
  #   set_property :delta => true

  # end











  #def to_indexed_json
  #  a = to_json(methods: [:answer])
  #  puts "#{'$' * 100}"
  #  puts a
  #  puts "#{'$' * 100}"
  #end
  #
  # def answer
  #  answers.collect{ |ans| ans.answer }
  #  tags.collect{|t| t.name}
  #  user.email
  
  #  Askquestion.first.tags.map(&:name).join(", ")
  #  user.email
  # end





  # def tag_names=(tokens)
  #   self.tag_ids = Tag.ids_from_tokens(tokens)
  # end









  after_save :assign_tags
def tag_names
  @tag_names || tags.map(&:name).join(' ')
end






  private
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\s+/).map do |name|
        Tag.find_or_create_by_name(name)
      end
      self.tags.each do |t|
        t.counter+=1
        t.save
      end
    end
  end












#validate :presence_of_tag_in_askquestion

#def presence_of_tag_in_askquestion
#  errors.add :tag, "must be a valid id" if self.tag_questions.blank?
#  errors.add :developed_bugs_id, "must be a valid developer id" if self.developer.blank?
end

app/models/askquestion_tag.rb
class AskquestionTag < ActiveRecord::Base
  # attr_accessible :title, :body
belongs_to :askquestion
belongs_to :tag

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :description
  validates :description, :presence => true

  belongs_to :commentable, :polymorphic => true
  belongs_to :user
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  attr_accessible :askquestion_id, :user_id
  belongs_to :user
  belongs_to :askquestion

  validates_uniqueness_of :user_id, :scope => [:askquestion_id]
end

app/models/inappropriate.rb
class Inappropriate < ActiveRecord::Base
  attr_accessible :askquestion_id, :user_id
  belongs_to :user
  belongs_to :askquestion

  attr_accessible :entity_id, :entity

   validates_uniqueness_of :user_id, :scope => [:entity_id, :entity]
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :name_event, :points
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :name, :counter

  has_many :askquestion_tags, :dependent => :destroy
  has_many :askquestions, :through => :askquestion_tags
  validates_uniqueness_of :name


  # def self.tokens(query)
  #   tags = where("name like ?", "%#{query}%")
  #   if tags.empty?
  #     [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
  #   else
  #     tags.map { |tag| {id: "#{tag.id}", name: "#{tag.name} X #{Tag.find_by_id(tag.id).askquestions.count}"} }
  #     #tags.map{|lan| [lan, Tag.find_by_name(lan).askquestion_tags.count]}

  #   end

  # end


  # def self.ids_from_tokens(tokens)

  #   tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
  #   tokens.split(',')

  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :username, :email, :password, :password_confirmation, :authentications_attributes

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  validates_confirmation_of :password
  validates :password, :presence => true, :on => :create
  validates :email, :presence => true
  validates :username, :presence => true
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  validates_format_of :email, :with => /[a-zA-Z0-9_-]+\@[a-zA-Z0-9_-]+\.\w+/

  has_many :askquestions,:dependent => :destroy
  has_many :answers
  has_many :votes
  has_many :comments

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # attr_accessible :title, :body

  belongs_to :votable, :polymorphic => true
  belongs_to :user

  validates_uniqueness_of :user_id, :scope => [:votable_id, :votable_type, :user_id]
end

app/models/watch.rb
class Watch < ActiveRecord::Base
  attr_accessible :askquestion_id, :user_id
  belongs_to :user
  belongs_to :askquestion

  validates_uniqueness_of :user_id, :scope => [:askquestion_id]
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_nav(user)

    #logger.info '=ELSE casr in HELPER='*10
    #logger.info current_user.inspect
    #logger.info '=Else -END- ='*20
    status = if user.present?

      "#{link_to('Log out', logout_path, :class => 'log-Out')} <span class='loged-user'>Logged in as #{user.email}.</span>".html_safe

      else

      "<li><a class='fancybox' href='#{login_path}' title='login' id='fancybox'>login</a></ li>".html_safe

    end
    "<ul><li><a href='#'>Faq</a></li> #{status} </ul>".html_safe
  end

  def is_active(action)       
    params[:action] == action ? "active" : nil        
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_view_helper.rb
module UsersViewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coding Stack</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "style" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery_ujs" %>
  <%#= stylesheet_link_tag "style.css" %>
  <%#= stylesheet_link_tag "jquery.fancybox" %>
  <%= csrf_meta_tag %>
  <!--<link rel="stylesheet" type="text/css" href="../source/jquery.fancybox.css?v=2.0.6" media="screen"/>-->
  <script type="text/javascript">

      $(document).ready(function () {
          $('.fancybox').fancybox({
//              'hideOnContentClick':false
          });
          

          $("form.login-form-base").submit(function (e) {
              e.preventDefault();
              console.log($("form.login-form-base").attr("action"));
              $.ajax({
                  type:"POST",
                  url:$("form.login-form-base").attr("action"),
                // beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                  data:$('form.login-form-base').serialize(),
                  success:function (data) {
                      //alert(data);
                      $.fancybox.close();
//                        console.log(data.success);
//                        console.log(data.user_id);
//                      $('#new_askquestion').submit();
//                     alert('saved question.');
                  }

              });


          });



//          $('#signup-box').submit(function() {
//              var valuesToSubmit = $(this).serialize();
/////            var question_id = $('#question_id_of_edit_form').val();
//              $.ajax({
//                  type:'POST',
//                  url: '/sessions',
////                  data: valuesToSubmit,
//                  data: {'email' : $('#email').val(), 'password' :$('#password').val()},
//                  dataType: "json" ,
//                  success : function(json){
//                      $.fancybox.close();
////
//
////                      $('nav.login-menu').html("<%#= login_nav( @abc )%>");
////                      debugger
//                       $('nav.login-menu').html('Logged in as ' + json.email);
////                     alert("<%= current_user.present? %>");
//
//                     // current_user ||= session[:current_user_id];
//
//                      <!--<%#= session[:current_user_id] = json.id %>-->
//
////                      session[:user_id] = @current_user.id
//                      <!--<%= logger.info '=AJAZ=' * 20  %>-->
//                      <!--<%= logger.info current_user %>-->
//                      <!--<%= logger.info '-=AJAZ-END=-' * 20 %>-->
//
//
////                      alert(test);
//                      //$('#loged-user').html("<%#= current_user %>");
////                      $('#fancybox').html('Logged in as ' +$('#email').val());
////                      alert(json);
//
//                  }
//              });
//              return false; // prevents normal behaviour
//          });//ending update attributes




      });

  </script>

</head>
<body class="<%= params[:controller] %>" onload="prettyPrint()">
<div id="wrapper">
  <header id="header">
    <div class="holder">
      <h1 class="logo"><a href="<%= root_path %>">coding stack</a></h1>
      <nav class="login-menu" id="loginmenu">
        <%= login_nav(current_user) %>

       </nav>
    </div>
    <nav id="nav">
      <ul>
        <li><a href="<%= askquestions_path %>">Questions</a></li>
        <li><a href="#">Tags</a></li>
        <li><%= link_to "Questions", askquestions_path %></li>
        <li><a href="#">Users</a></li>
        <li><a href="#">Badges</a></li>
        <li><a href="<%= unanswered_path %>">Unanswered</a></li>
        <li><a href="#">Pages</a></li>
      </ul>
      <ul class="ask-q">
        <li><a href="<%= new_askquestion_path %>">Ask Questions</a></li>
      </ul>
    </nav>
  </header>
  <div id="container">
    <div class="user_nav">
      <!--
      <%# if current_user %>-->
          <!--Logged in as <%#= current_user.email %>.-->
          <!--<%#= link_to "Log out", logout_path %>-->
          <!--
      <%# else %>-->
          <!--<ul>-->

          <!--&lt;!&ndash;<li><a class="fancybox" href="#inline2" title="login">login</a></li>&ndash;&gt;-->
          <!--</ul>-->
          <!--
      <%# end %>-->
    </div>
    <% unless flash[:notice].blank? %> 
      <div id="notification" class="alert alert-notice"><%= flash[:notice] %></div> 
    <% end %>
    <% unless flash[:error].blank? %> 
      <div id="notification" class="alert alert-error"><%= flash[:error] %></div> 
    <% end %>
    <% unless flash[:message].blank? %> 
      <div id="notification" class="alert alert-message"><%= flash[:message] %></div> 
      <%cookies[:username] = current_user.email%>
    <% end %>
    <%= yield %>
  </div>


  <section id="main">
    <div id="inline1" style="width:500;display: none;" class="light-box">
      <div class="b-top">&nbsp;</div>
      <div class="b-center">
        <div class="box-signup">
          <% user = User.new %>
          <%= form_for user , :html => {:class => "login-form-base"}  do |f| %>
              <% if user.errors.any? %>
                  <div class="error_messages">
                    <!--<h2>Form is invalid</h2>-->
                    <ul>
                      <% for message in user.errors.full_messages %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <div class="user-holder">
                <label class="user-text">Email</label>
                <%= f.text_field :email, :class => "txt-field5" %>
              </div>
              <div class="user-holder">
                <label class="user-text">password</label>
                <%= f.password_field :password, :class => "txt-field5" %>
              </div>
              <div class="user-holder">
                <label class="user-text">confirm password</label>
                <%= f.password_field :password_confirmation, :class => "txt-field5" %>
              </div>
              <div class="submit-holder">
                <div class="actions sign-btn"><%= f.submit %> </div>
                <!--<a class="fancybox sign-in-btn" href="#inline2" title="login">login</a>-->

              </div>
          <% end %>
              </div>

              <ul class="feature-holder">

                <li><a href="<%= auth_at_provider_path(:provider => :google) %>" class="google-icon"></a></li>

                <li><a href=" <%= auth_at_provider_path(:provider => :facebook) %>" class="facebook-icon"></a></li>


                <li><a href="<%= auth_at_provider_path(:provider => :twitter) %>" class="twitter-icon"></a></li>


                <li><a href=" <%= auth_at_provider_path(:provider => :github) %>" class="github-icon"></a></li>
              </ul>
              </div>
              <div class="b-btm">&nbsp;</div>

          </div>
  </section>


  <div id="inline2" style="width:500;display: none;" class="light-box">
    <div class="b-top">&nbsp;</div>
    <div class="b-center">
      <div class="box-signup" id="signup-box">
        <%#= form_tag sessions_path, :html => {:class => "login-form-base1"}, remote: true, :url => sessions_path, :update => { :success => "usersssssss", :failure => "errorrrrrr" },  :method => :post do %>
        <%= form_tag sessions_path, :method => :post  do %>
            <%#= form_tag sessions_path, :html => {:class => "login-form-base1"} do %>
            <div class="user-holder">
              <label class="user-text">Email</label>
              <%= text_field_tag :email, params[:email], :class => "txt-field5",:placeholder => 'Email' %>
            </div>
            <div class="user-holder">
              <label class="user-text">Password</label>
              <%= password_field_tag :password,'', :class => "txt-field5",:placeholder => 'Password' %>

            </div>
            <div class="user-holder">
              <label class="user-text">remember me</label>
              <%= check_box_tag :remember_me, 1, params[:remember_me],:class =>"check-Box" %>
            </div>
            <div class="actions submit-holder"><%= submit_tag "Log in",:class =>"sign-btn sign-in-btn"  %>
              <span class="text-or">or</span>
              <a class="fancybox sign-btn" href="#inline1" title="Sign Up">signUp</a>
            </div>

        <% end %>

      </div>
      <ul class="feature-holder">
        <li><a href="<%= auth_at_provider_path(:provider => :google) %>" class="google-icon"></a></li>

        <li><a href=" <%= auth_at_provider_path(:provider => :facebook) %>" class="facebook-icon"></a></li>


        <li><a href="<%= auth_at_provider_path(:provider => :twitter) %>" class="twitter-icon"></a></li>


        <li><a href=" <%= auth_at_provider_path(:provider => :github) %>" class="github-icon"></a></li>
      </ul>
    </div>
    <div class="b-btm">&nbsp;</div>

  </div>

  <footer id="footer">
    <span>All <a href="#">codingstack.com</a> content and data are available under the Creative Commons Attribution 3.0 license</span>
<span><a href="#">blog</a> | <a href="#">twitter</a> | <a href="#">buzz</a> | <a href="#">identi.ca</a> | <a href="#">code</a> | <a href="#">irc
  (web chat)</a> | <a href="#">feedback</a> | <a href="#">tos</a> | <a href="#">privacy</a></span>
    <span>Powered by <a href="#">codingstack.com</a> under the GNU Affero General Public License</span></footer>
</div>
</div>


</body>
</html>

app/views/layouts/login_fancy.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Coding Stack</title>
      <%= favicon_link_tag 'favicon.ico' %>
      <%= stylesheet_link_tag "application" %>
      <%= javascript_include_tag "application" %>
      <%#= javascript_include_tag "jquery.tokeninput.js" %>
      <%#= stylesheet_link_tag "style.css" %>
      <%#= stylesheet_link_tag "jquery.fancybox" %>
      <%= csrf_meta_tag %>

  </head>
<body>
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>
</body>
</html>

app/views/shared/_questions_index.html.erb
<% @askquestions.each do |question| %>
    <input type="hidden" name="<%= question.id %>_Q_user_id" id="<%= question.id %>_Q_user_id" value="<%= question.user_id %>" >
    <div class="q-post-holder">
      <div class="q-post">
        <div class="q-top">
          <div class="counter-holder">
            <ul class="counter-nav">
              <li><span class="votes_count_<%= question.id%>"> Votes: <%= question.votes.sum(:status) %> </span></li>
              <li class="green-bg"><span>Answer: <%= question.answers.count %></span></li>
              <li><span>View: <%= question.view_counter %></span></li>
            </ul>
            <strong class="by-date"> <span class="u-name"><a href="/users/<%= question.user.id %>"><%= question.user.email.gsub(/@.*/, "") %></a> <%= question.user.rating %></span>
              <span>Asked<span class="ago-days"> <%= time_ago_in_words(question.created_at) %> ago</span></span>
            </strong>
          </div>
          <div class="middle-holder">
            <div class="user-question">
              <span class="user-img"><%= image_tag avatar_url(question.user) %><!--<img src="/assets/img-1.jpg" width="42" height="42" alt="image"/>--></span>

              <p class="question-txt ">
                <a href=<%=new_askquestion_answer_path(question.id) %>><%= raw(question.title) %></a>
              </p>
            </div>
            <div class="tags-holder"><span class="tag-name">tags:</span>
              <ul class="question-tags">

                <% question.tags.each do |a| %>
                    <li><a href="#"><%= a.name %></a></li>
                <% end %>
                <!--<li><a href="#">tag 2</a></li>-->
              </ul>

              <div class="about-question">
                <div class = "ques_<%= question.id%>">

                  <% if current_user && current_user.votes.where(votable_id:question.id ,Votable_type: "Askquestion").present?   %>

                      <% if current_user.votes.where(votable_id:question.id , Votable_type: "Askquestion").last.status == 1 %>
                          <input type="hidden" name="question_id" class="question_id" value='<%= question.id %>' />
                          <%= link_to  "VOTE DOWN", 'javascript:void(0);', :class => "unlike-down", :id => "vote_down_#{question.id}", :data => question.id  %>

                      <% elsif current_user.votes.where(votable_id: question.id , Votable_type: "Askquestion").last.status == -1   %>

                          <%= link_to 'VOTE UP',  'javascript:void(0);', :class => "like-up", :id => "vote_up_#{question.id}" , :data => question.id    %>
                          <input type="hidden" name="question_id" class ="question_id" value='<%= question.id %>' />
                      <% end %>
                  <% else %>
                      <%= link_to 'VOTE UP', 'javascript:void(0);', :id => "vote_up_#{question.id}", :class => "like-up" , :data => question.id  %>
                      <input type="hidden" name="question_id" id="question_id" value='<%= question.id %>' />
                      <%= link_to  "VOTE DOWN", 'javascript:void(0);', :id => "vote_down_#{question.id}", :class => "unlike-down", :data => question.id  %>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="q-btm">&nbsp;</div>
      </div>
    </div>
<% end %>

app/views/shared/_tags_all.html.erb
<div class="tags-title">
  <ul class="tags-nav">
    <% Tag.all.each do |a| %>
        <li><a href="<%= root_path%>askquestions?utf8=✓&search=<%= a.name%>"><%= a.name %> (<%= AskquestionTag.find_all_by_tag_id(a.id).count %>) </a></li>
    <% end %>
    <!--<li><a href="#">php</a></li>
   <li><a href="#">google</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">php</a></li>
   <li><a href="#">google</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">php</a></li>
   <li><a href="#">google</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">google</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">php</a></li>
   <li><a href="#">google</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">php</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">php</a></li>
   <li><a href="#">google</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">php</a></li>
   <li><a href="#">google</a></li>
   <li><a href="#">javascript</a></li>
   <li><a href="#">css</a></li>
   <li><a href="#">php</a></li>
   <li><a href="#">google</a></li>-->
  </ul>
</div>

app/views/shared/_users_right_bar.html.erb
<div class="user-holder"><strong class="user-heading">Top 5 users</strong>
  <ul class="user-bio">
    <% User.order("rating DESC").limit(5).each do |u| %>
        <li>
          <span class="user-icon"><%= image_tag(avatar_url(u), :width=> 34, :alt => 'no image') %></span>
          <span class="user-proxi"><a href="users/<%= u.id %>"><%= truncate(u.email.gsub!(/@.*/, ""), :length => 12)%> </a>(<%= u.rating %>)</span>
        </li>

    <% end %>
   </ul>
</div>

<div class="user-holder"><strong class="user-heading">Recent users</strong>
      <ul class="user-bio">
        <% User.order("created_at DESC").limit(5).each do |u| %>
        <li>
          <!--<span class="user-icon"><img src="/assets/img-1.jpg" width="34" height="33" alt="image"/></span>-->
          <span class="user-icon"><%= image_tag(avatar_url(u), :width=> 34, :alt => 'no image') %></span>
          <span class="user-proxi"><a href="users/<%= u.id %>"><%= truncate(u.email.sub!(/@.*/, ""), :length => 12)%> </a>  joined <%= time_ago_in_words(u.created_at) %></span>

        </li>
    <% end %>
  </ul>
</div>
<div class="stay-us"><span class="stay-heading">Stay in touch</span>

    <div class="facebook-plugin"><img src="/assets/coding-stack-img.png" width="271" height="60" alt="facebook">
    </div>
    <span class="stay-heading">subscribe</span> <a href="#" class="rss-field">Subscribe to all questions</a>
</div>